### ISSUE TITLE
Digital Rights Management should not be in scope

### ISSUE THREAD

**Issue by dbaron** [w3c/dpubwg-charter#15] opened 2017-02-22 00:05 UTC
The [proposed charter for a Digital Publishing WG](https://w3c.github.io/dpubwg-charter/) references a number of input documents, one of which is the [EPUB 3.1 member submission](https://www.w3.org/Submission/2017/SUBM-epub31-20170125/).  One of the six documents in this submission is [EPUB Open Container Format (OCF) 3.1](https://www.w3.org/Submission/2017/SUBM-epub-ocf-20170125/), which contains a [section on Digital Rights Management (DRM)](https://www.w3.org/Submission/2017/SUBM-epub-ocf-20170125/#sec-container-metainf-rights.xml).

While the W3C has another area of work, [Encrypted Media Extensions (EME)](https://www.w3.org/TR/encrypted-media/), that covers DRM, the DRM proposed here has substantially broader implications since it is a DRM that covers the core Web technologies (HTML, CSS, Javascript, etc.).  It is different from EME because:

1. Video DRM was already a major use case for plugins (Silverlight and Flash), and the lack of video DRM in the Web platform was an obstacle to the retirement of the NPAPI and ActiveX plugin APIs, which has historically been a bigger obstacle to the portability of the Web across devices, and the security and stability of the Web for its users, than EME has.

2. Video decoding is quite isolated from the implementation of other Web technologies, and even without DRM is often done in a separate external component; application of DRM to core Web technologies could affect entire browser engines.

DRM should be out of scope in this charter, so that the W3C does not standardize DRM that applies to its own core Web technologies.

**Comment by iherman** [comment] 2017-02-22 04:18
@dbaron, the current proposed charter already lists DRM explicitly as being out of scope in the [relevant section](https://w3c.github.io/dpubwg-charter/#out-of-scope).

**Comment by dbaron** [comment] 2017-02-22 05:44
Ah, that's good to see.  (It's possible I missed it because I was searching for "Rights", as DRM is typically expanded as "Digital Right**s** Management".)

**Comment by iherman** [comment] 2017-02-22 05:46
... which shows that it is probably a good idea to expand the acronym! I mark this issue as editorial...

**Comment by tantek** [comment] 2017-02-22 08:48
Minor nit (in looking at charter txt as of now): 
s/Digital Right Management/Digital Rights Management

**Comment by tantek** [comment] 2017-02-22 11:07
Why the parenthetical "(however, the Working Group shouldn’t make any design decision that would make such features impossible) " ? That seems both antithetical to the intent, and frankly, a source of possible abuse, that is, could be twisted to argue, by not making such feature impossible, you must allow for an EME-like mechanism. I'd prefer to simply leave out that parenthetical.

**Comment by GarthConboy** [comment] 2017-03-13 13:14
A little history: EPUB (for all it's relevance, or lack thereof) is an unencrypted and un-DRM-ed format [which matches my religion, FWIW].  In EPUB there are "hooks" available to which signatures, encryption, and DRM could be attached.  Left completely unspecified, however.

We need to ensure, for PWP to be adopted in practice by the publishing industry, that we don't do something that would prohibit WP/PWP to be wrapped in some DRM.  Though, we're going to take no part in said definition.

At the BG meeting on March 13th we liked "(while it remains out of scope, however, the Working Group shouldn’t make any design decision that would make such features impossible)" as a replacement parenthetical.

**Comment by jar398** [comment] 2017-03-21 13:46
Ivan has asked me to move the statement of #43 to this issue. I agree that #43 is generally on the subject, but I do not think that resolving this issue (#15) would resolve #43, unless there were a decision to remove any mention (including the wording suggested above) from the draft. Because this is a different question from the one that was raised, I made it a separate issue.

However I defer to Ivan. The following is what I wrote in #43.

Without prejudice concerning whether DRM should be in scope, the draft currently puts it in scope, lightly, with the comment "the Working Group shouldn’t make any design decision that would make such features impossible" (belying the section's title).

If there is language like that for DRM, then there should also be parallel language regarding legal use of content, such as reproduction of public domain or open access works, and exercise of fair use and related rights. That is, something like: "the Working Group shouldn’t make any design decision that would make legal reproduction or exercise of fair use rights impossible".

**Comment by mattgarrish** [comment] 2017-03-22 07:53
The DRM statement is a bit confusing. Can something be out of scope and at the same time in scope to not affect it?

Since I guess it has to go somewhere, it might be better if this followed the list so could be explained without the long parenthetical. A thought would be to just have "Digital rights management schemes" with an asterisk in the list followed by a one-sentence paragraph like:

"While the application of any required digital rights management scheme is out of scope for Web Publications, the Working Group will take into consideration in their design decisions that some content producers need to apply such schemes."

Fair use design decisions is a little harder for me to wrap my head around. Trying to get away from a legal question, would the technology equivalent be that Web Publications should be built on open source and patent unencumbered technologies? With the exception of video, that's the route that EPUB took. Or will the concept of core media types be restricted to an epub profile only? It's hard to tell from the scope section, as the only relevant bit is that resources "may be presented using standard Open Web Platform technologies".

**Comment by iherman** [comment] 2017-03-22 09:48
@mattgarrish, I believe that putting any reference to DRM anywhere else than in the “out of scope” section would lead to an infinite amount of discussions; I would prefer to avoid that. Ie, I would prefer to go along the lines of what we have now: put a clear stake in the ground that we will _not_ develop any type of DRM, but accompany it with a clear(er) statement that we will not create artificial barriers either.

> Fair use design decisions is a little harder for me to wrap my head around. Trying to get away from a legal question, would the technology equivalent be that Web Publications should be built on open source and patent unencumbered technologies? With the exception of video, that's the route that EPUB took.

I think that is the situation we are in, simply because we do build on OWP technologies. I am not sure it is worth going into the details of that. But, I believe, @jar398‘s argument is a little bit different…

@jar398, I take your point, and we may indeed have address both sides, so to say. Here is a text I have come up with, which tries to combine these. For the sake of readability I have to whole proposed bullet point here:


>Digital Rights Management (DRM) for Web Publications. The design of Web Publications should be strictly neutral in this respect. This means the Working Group shouldn’t make any design decision that would make the implementation of DRM, or to open up the publication for legal reproduction and exercise of fair use rights, impossible.


WDYT? 

/CC @GarthConboy

**Comment by mattgarrish** [comment] 2017-03-22 14:05
Yes, I wasn't arguing that we move it to in-scope, although technically it is in scope as far as it necessitates design decisions that don't prevent it.

But how do we say that DRM must be removable to ensure fair use, even though DRM isn't in scope? That's the problem I couldn't quite wrap my head around as far as a design principle to follow. Or does "open up" in this case mean no barrier of any kind to accessing the internals even with no DRM?

If so, could that be made clearer by not connecting the two statements? For example, do we even need to take a neutral stance, or can we favour one approach while allowing for the other, as in:

> Digital Right Management (DRM) for Web Publications. The design of Web Publications must favour an open framework that does not impinge on the legal reuse, reproduction and exercise of fair use rights. At the same time, the Working Group should not make any design decisions that would make the implementation of DRM on top of this framework impossible.

And to my resource-level question, building on open web technologies doesn't in itself lead to interoperability or the use of non-proprietary, patent-free technologies. But, if it's not in scope for the general profile, or not something you want to delve into in the charter, I can live with that. I just hope it retains priority on the epub side for all the usability and accessibility benefits that come with it.

**Comment by WSchindler** [comment] 2017-03-22 15:20
In the interest of fair use and accessibility, I would prefer to keep Web Publications (like EPUB) as an open, non-proprietary, patent-free and easily accessible format without intrinsic DRM mechanisms. 

As DRM is primarily a legal issue with technical implementations, it is of course out of scope for the Publishing WG, but I would restrict ourselves in this issue to say that we don't intend to make its implementation impossible.

As W3C, we should in my opinion be very much in favour of open frameworks and I think it makes a lot of sense to express that explicitly in this charter.

I'm thus in favour of @mattgarrish's proposal which I see as very adequate.

**Comment by GarthConboy** [comment] 2017-03-22 15:42
I find Matt's suggestion two comments above:

_Digital Right Management (DRM) for Web Publications. The design of Web Publications must favor an open framework that does not impinge on the legal reuse, reproduction and exercise of fair use rights. At the same time, the Working Group should not make any design decisions that would make the implementation of DRM on top of this framework impossible._

to be accurate and an improvement over current language.  I will ping the DPUB BG for their concurrence.

**Comment by mattgarrish** [comment] 2017-03-22 16:09
s/Right/Rights/

Bad retype on my part.

**Comment by rickj** [comment] 2017-03-22 16:41
I'm having cognitive dissonance with the initial "must" and the subsequent "should".  They need to match.  IMO, if the open framework is a must, the design decision statement has to be a must also.  I do not favor that, however; I believe they should both be a "should".

**Comment by mattgarrish** [comment] 2017-03-22 18:01
That's fine with me.

I was considering framework along the lines of manifest, packaging, etc., with DRM as a separate layer with only a hook like EPUB has. That makes the statements largely disconnected. But I suppose when considering the format in total as the framework then a "must favour" may be too strong, even if it isn't exclusionary. Industry standard technologies have been known to trip up our best intentions for free and open.

**Comment by iherman** [comment] 2017-03-22 18:55
@rickj, I agree that both sentences must (sic!:-) be a musts or shoulds. However, I have the impression that a "must" makes both statements stronger, ie, I am, at this moment, more in favour of a "must" on both places.

**Comment by laudrain** [comment] 2017-03-22 19:18
Fine with me too.
And 2 "must" is a strong position I support.

**Comment by rickj** [comment] 2017-03-23 02:16
I'm happy with both as a "must" as well.  My initial preference was out of an abundance of caution and sensitivity.

This closes this issue in my mind.

**Comment by iherman** [comment] 2017-03-23 07:09
I have made a new commit in the relevant branch; to make it clear, it now says:

>Digital Rights Management (DRM) for Web Publications.
> The design of Web Publications must favour an open framework that does not impinge on the legal reuse, reproduction and exercise of fair use rights.
> At the same time, the Working Group must not make any design decisions that would make the implementation of DRM on top of this framework impossible.

which seems to reflect the current consensus, so I thought it better to replace the previous text in the branch which has been superseded. The text is still in a separate Pull Request (#30), ie, not yet incorporated into the final text.

**Comment by dbaron** [comment] 2017-03-28 14:12
Like my colleague @tantek's https://github.com/w3c/dpubwg-charter/issues/15#issuecomment-281638877 on the earlier proposed text, I'm still not comfortable with the second sentence there.

The Web Publications work is itself built on top of many other Web technologies, and having a requirement that Web Publications not make design decisions that would make DRM impossible appears to impose that same requirement on all the technologies underneath them.  These technologies (HTML, CSS, DOM APIs, Javascript, etc.) don't currently have such a requirement, and I don't want to impose such a requirement on them, or to impose the (technical and other) concerns of being part of a DRM system on their implementations.

**Comment by citizencontact** [comment] 2017-03-28 15:59
I would separate out issues of DRM from other aspects of legal use. I believe any system should built and analyzed based on a BLT methodology (business issues such as transactions and use, legal issues such as jurisdiction, and at the bottom, technical implementation). So if these epubs and html documents should have the hooks for digital signing/hashing using XML Digital Signatures (https://www.w3.org/TR/xmldsig-core/), machine readable copyright assertions and other legally required metadata by jurisdiction, ability to be cited, granular authentication, and other important factors. DRM is an important use case issue, where those selling should report back on whether epub is equal to other formats in allowing this regime. I think with digital signing/hashes as part of the standard, this may be important.

**Comment by HadrienGardeur** [comment] 2017-03-28 16:13
We should draw a line between WP and PWP/EPUB regarding DRM.

As it's been pointed out before, DRM for WP is a non-starter, even purely from a technological standpoint.

PWP is different since we'll most likely have a package and the ability to handle DRM in a similar way as EPUB.

**Comment by graham-bell** [comment] 2017-03-28 16:41
@dbaron – I don't in any way disagree that DRM is out of scope, but I would imagine that a lot of people would be looking for some clarification of that (particularly in the light of the fact that there has been so much discussion on this point). Can I suggest

Out of scope: DRM (for the avoidance of doubt, this means that the WG should not make any decision that would either require or prevent the application of DRM technologies)

Graham

**Comment by llemeurfr** [comment] 2017-03-28 16:45
@graham-bell 's proposal seems good, as it makes the WG neutral about this DRM aspect.

**Comment by JensKlingelhoefer** [comment] 2017-03-29 14:52
I agree with Graham's proposal. Otherwise we would certainly see a lot of discussions outside this group about what "out of scope" would actually mean.

**Comment by iherman** [comment] 2017-04-03 03:45
The pull request #30 reflects the [proposal](https://github.com/w3c/dpubwg-charter/issues/15#issuecomment-289830577) of @graham-bell.

**Comment by wseltzer** [comment] 2017-04-05 08:38
I'd recommend that we leave it at "DRM is out of scope." If there's ambiguity in the meaning of out-of-scope, the WG can resolve it at a later date.

**Comment by GarthConboy** [comment] 2017-04-05 13:21
If folks generally happy with the proposed (Graham's) solutions:

Out of scope: DRM (for the avoidance of doubt, this means that the WG should not make any decision that would either require or prevent the application of DRM technologies)

I would go with that, rather than shortening further.

**Comment by llemeurfr** [comment] 2017-04-05 13:44
I'm fine with this solution.
Laurent Le Meur
CTO, EDRLab

**Comment by jar398** [comment] 2017-04-05 13:45
In answer to the question "are folks generally happy with proposed solution" please see my comment above. Wendy's suggestion is consistent with what I requested, and I think it's fine; Graham's proposed solution is not since it puts a stake in the ground, while pretending not to.

You asked.

**Comment by mattgarrish** [comment] 2017-04-05 13:58
Would it help to get away from decision making and technology compatibility and instead state what is necessary:

Out of scope: DRM -- except optional hook(s) that allow for the application of

**Comment by jar398** [comment] 2017-04-05 14:00
It wouldn't help me. Did you read my previous comment, the one beginning "Ivan has asked me to"?

**Comment by jar398** [comment] 2017-04-05 14:07
I think if the charter had Wendy's wording, and then the WG decided to work on the hooks (which we know it will try to do), then it has plausible deniability, since working on the hooks is not working on DRM.  So I'm not sure what there is to fear in Wendy's proposal.

**Comment by mattgarrish** [comment] 2017-04-05 14:12
I tried to answer that above, but am not sure if any of that prose is still being considered. It could be wrapped up into one statement like:

"The design of Web Publications must favor an open framework that does not impinge on the legal reuse, reproduction and exercise of fair use rights. Digital right management schemes are therefore not in scope, but optional hook(s) that allow for their application are."

**Comment by pbelfanti** [comment] 2017-04-05 14:18
If Wendy’s proposed wording is the path of least resistance, and keeps certain options (or plausible deniability) open, I’m fine with that.

Paul
—
Paul Belfanti
VP, Production, Manufacturing & Content Architecture
(w) 978.639.3536
(m) 201.783.4884

**Comment by mattgarrish** [comment] 2017-04-05 14:20
I'm fine with that, too, to be honest.

I'm just floating alternatives to see if they can make everyone a little happier, and seem to miss updates while I'm typing.

**Comment by jar398** [comment] 2017-04-05 14:20
@mattgarish Sorry. Yes, with the quoted wording, or something like that, my comment is addressed.  I was limiting my response to what I saw in your latest comment. So either solution is fine. I will try to shut up now (again).

**Comment by HadrienGardeur** [comment] 2017-04-05 14:21
DRM is truly out of scope for this group and there's no need for "DRM specific hooks".

As long as the specification provides a mechanism for dealing with encrypted resources in PWP/EPUB4 that's enough.

**Comment by GarthConboy** [comment] 2017-04-05 15:00
Yes, Jonathan ( @jar398 ), I did grok your comment -- just not 100% on board.  :-)

But, that said, as we really need to close this and move on (and leave details to the actual WG), I "can live with" Wendy's ( @wseltzer  ) minimal verbiage.

Alternately, we could combine Graham's and Jonathan's to:

"Out of scope: DRM (for the avoidance of doubt, this means that the WG should not make any decision that would either require or prevent the application of DRM technologies, likewise, the WG should not make any design decision that would make legal reproduction or exercise of fair use rights impossible)."

And I'm also fine with Matt's (with a very slight tune):

"The design of Web Publications must favor an open framework that does not impinge on the legal reuse, reproduction and exercise of fair use rights. Digital right management schemes are therefore not in scope, but optional hook(s) that allow for their application may be."

Geeze... I'm just about fine with everything this morning!

**Comment by llemeurfr** [comment] 2017-04-05 15:03
Matt's wording is good (also). +1

**Comment by rickj** [comment] 2017-04-05 15:15
As much as I'd like to agree with Jonathan or Matt's wording, unfortunately, they both take us down the path of needing to delineate and define "fair use rights", and I don't want to take the charter down that path.

We need to get this into the hands of the WG, so I'm in favor of Wendy's minimalist, or Graham's minimalist + wording.

**Comment by iherman** [comment] 2017-04-05 22:29
I am in favor of cutting the discussion which can go on forever. The minimalist view of @wseltzer means that we can move on at last, and I actually have trust in all parties around the table that the WG will not do anything crazy in either direction. Ie: declare the DRM to be out of scope and not try to get into explanations.

**Comment by rickj** [comment] 2017-04-06 00:42
Accepting the minimalist view as detailed by @wseltzer  in https://github.com/w3c/dpubwg-charter/issues/15#issuecomment-291793353, and restating her comment "If there's ambiguity in the meaning of out-of-scope, the WG can resolve it at a later date." we are officially closing this issue.

**Closed as completed** 2017-04-06 00:42 UTC
Labels: General Comment
